"""empty message

Revision ID: 230cbdc272d8
Revises: 3e06c1fbbeff
Create Date: 2020-08-22 17:14:03.447907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230cbdc272d8'
down_revision = '3e06c1fbbeff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('artist', 'seeking_performance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_performance', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
