"""empty message

Revision ID: a8a0a1bd8f95
Revises: 230cbdc272d8
Create Date: 2020-08-22 17:56:17.034025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8a0a1bd8f95'
down_revision = '230cbdc272d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('artist', 'shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('shows', postgresql.ARRAY(postgresql.TIMESTAMP()), autoincrement=False, nullable=True))
    op.drop_table('shows')
    # ### end Alembic commands ###
